config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'

  resources :users
  resources :events, only: [:new, :create, :destroy, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login

    def require_login
        if session[:current_user]
            @current_user = session[:current_user]
        else 
            redirect_to login_path, :alert => 'Sign up or Log in to see the events!'
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  def new
    @event = Event.new
  end

  def index
    @event = Event.all
  end

  def show
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event details are saved" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :location, :date, :about, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user
      session[:current_user] = user
      redirect_to events_path, notice: "Logged in!"
    else
      flash.now.alert = "Name is invalid"
      render 'new'
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy]
  def new 
    @user = User.new
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User details are saved" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_member
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :address, :age, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<ul>
    <% @event.each do |event| %>
        <li><%= event.name %></li>
    <% end %>
</ul>

app/views/events/new.html.erb
<%= form_with model: @event , :class => "form" do |form| %>
    <div style="padding: 3%">
        <div>
            <%= form.label :name %>
            <%= form.text_field :name , :placeholder => 'Enter the Name' %>
        </div><br/>

        <div>
            <%= form.label :location %>
            <%= form.text_field :location , :placeholder => 'Enter the Location' %>
        </div><br/>

        <div>
            <%= form.label :about %>
            <%= form.text_area :about , :placeholder => 'Enter the Description' %>
        </div><br/>
        
        <div>
            <%= form.label :date %>
            <%= form.date_field :date , :placeholder => 'Enter the Age' %>
        </div><br/>
        
        <div>
            <%= form.hidden_field :user_id , value: session[:current_user][:id] %>
        </div>
        <%= form.submit %>
    </div>
<% end %>

app/views/events/show.html.erb
<h1>In Show</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>About Event:</strong>
  <%= @event.about %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <span style="float:right"><%= link_to 'Logout' , logout_path %></span>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with model: @user , :class => "form" do |form| %>
    <div style="padding: 3%">
        <div>
            <%= form.label :name %>
            <%= form.text_field :name , :placeholder => 'Enter the Name' %>
        </div><br/>

        <div>
            <%= form.label :address %>
            <%= form.text_field :address , :placeholder => 'Enter the Address' %>
        </div><br/>

        <div>
            <%= form.label :phone %>
            <%= form.number_field :phone , :placeholder => 'Enter the Phone' %>
        </div><br/>
        
        <div>
            <%= form.label :age %>
            <%= form.number_field :age , :placeholder => 'Enter the Age' %>
        </div><br/>
        <%= form.submit %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_with model: @user , :class => "form" do |form| %>
    <div style="padding: 3%">
        <div>
            <%= form.label :name %>
            <%= form.text_field :name , :placeholder => 'Enter the Name' %>
        </div><br/>

        <div>
            <%= form.label :address %>
            <%= form.text_field :address , :placeholder => 'Enter the Address' %>
        </div><br/>

        <div>
            <%= form.label :phone %>
            <%= form.number_field :phone , :placeholder => 'Enter the Phone' %>
        </div><br/>
        
        <div>
            <%= form.label :age %>
            <%= form.number_field :age , :placeholder => 'Enter the Age' %>
        </div><br/>
        <%= form.submit %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1>In Show</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>